### ISSUE TITLE
Is there a way to not expose the app on public network?

### ISSUE THREAD

**Issue by ilgigante77** [yellowsink/ouroboros#2]
As per title, I would like to keep my instance of this app in the LAN/VPN side, though HS is exposed for obvious reasons. Is it possible?

**Comment by yellowsink** [comment]
you can access the server's tailscale IP and the correct port /ouroboros and it'll work as you expect, or just reverse proxy however you want (I've been able to find caddy setups that only allow internal connections)
but the main feature I really wanted here was the /register override, which obviously needs to be public.

you can make it private though, just don't expose the endpoints via a reverse proxy.

**Comment by ilgigante77** [comment]
And the GitHub app which callback URL should have in this case?

Il ven 25 ott 2024, 12:05 Hazel Atkinson ***@***.***> ha
scritto:

**Comment by yellowsink** [comment]
I don't see why your callback URL couldn't be e.g. http://100.64.0.6:8080/ouroboros/auth/callback

**Comment by ilgigante77** [comment]
Thanks this was unclear to me

Il ven 25 ott 2024, 12:19 Hazel Atkinson ***@***.***> ha
scritto:
